DROP TABLE IF EXISTS fruits CASCADE;
DROP TABLE IF EXISTS pokemons CASCADE;

CREATE TABLE fruits (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT NOT NULL,
  taste TEXT NOT NULL,
  weight INTEGER NOT NULL
);

CREATE TABLE pokemons (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  height INTEGER NOT NULL,
  type TEXT NOT NULL,
  weight INTEGER NOT NULL
);
